Added most spells, fx.Charger
sindreslungaard/duel-masters pull request #211
Opened 2024-04-17 13:59 UTC by Zayberex

+cnd.Charger
+Energy Charger
+Freezing Icehammer
+Fruit of Eternity
+Hopeless Vortex
+Lightning Charger
+Miracle Portal
+Mulch Charger
+Riptide Charger
+Vacuum Gel
+Venom Charger
+updated repo

2024-10-09 20:27 UTC, DanieloV requested changes
This branch should be brought up-to-date with the current codebase, since some methods have been changed since it was created.

2024-10-09 20:27 UTC, DanieloV commented on game/cards/dm07/spells.go
> +			ctx.Match.Chat("Server", fmt.Sprintf("%s was given power attacker +2000", creature.Name))
This should use `PowerAmplifier` instead of `PowerAttacker`

2024-10-09 20:27 UTC, DanieloV commented on game/cards/dm07/spells.go
> +			ctx.Match.Chat("Server", fmt.Sprintf("%s was moved to %s's manazone", x.Name, x.Player.Username()))
All the ".Chat" calls need to be replaced by ".ReportActionInChat", which also take a player as a param. The player passed should be the owner of the moved card, if movement happens.

2025-05-11 19:31 UTC, sindreslungaard commented
Added in another PR

2025-05-11 19:31 UTC, closed without merging