Fix Ucarn chat message. Added Apocalypse Vise.
sindreslungaard/duel-masters pull request #289
Opened 2024-09-30 15:48 UTC by jyotiskaghosh

2024-10-03 13:36 UTC, DanieloV requested changes

2024-10-03 13:36 UTC, DanieloV commented on webapp/package-lock.json
This shouldn't be part of this PR. Also it's regressing the lockFileVersion, you probably should use a higher npm version if you want to update this file.

2024-10-03 19:13 UTC, jyotiskaghosh commented on webapp/package-lock.json
What's the current version? I just updated it cause I had some error running the webapp.

2024-10-04 06:05 UTC, DanieloV commented on webapp/package-lock.json
Just use the latest version

2024-10-06 01:51 UTC, merged