Add currently acceptable(DM-07) promo exclusives. Fix Cosmic Nebula and Xeno Mantis.
sindreslungaard/duel-masters pull request #293
Opened 2024-10-13 17:03 UTC by jyotiskaghosh

2024-10-14 13:56 UTC, DanieloV requested changes

2024-10-14 13:56 UTC, DanieloV commented on game/cards/promo/chimera.go
> +			false).Map(func(x *match.Card) {
This card is a `may destroy`. Should allow the select to be canceled as currently it's enforcing destruction.

2024-10-14 13:56 UTC, DanieloV commented on game/cards/promo/demon_command.go
> +	c.Use(fx.Creature, fx.Doublebreaker, func(card *match.Card, ctx *match.Context) {
This should be refactored into fx.When(fx.AnotherOwnCreatureDestroyed, fx.MayUntapSelf)

MayUntapSelf already exists
AnotherOwnCreatureDestroyed, doesn't exist, but there is AnotherCreatureDestroyed, so it could use it in it's implementation. 

When it come to `When`, the idea for the future is that when all cards with trigger effects implement `When/WhenAll` func, it will be a good candidate to refactor to better handle multiple trigger effects happening at the same time, by separately handling the validation step and the effect step (which this method already separates). That's also why with all the new cards added I also slowly refactored many of the existing cards to use When.

2024-10-14 13:56 UTC, DanieloV commented on game/cards/promo/angel_command.go
> +		}
This doesn't work as expected with cards that give blocker e.g. Full Defensor. I think this requires implementing ConditionalBlocker (akin to ConditionalSlayer). And then when the blockers list is assembled for AttackCreature and AttackPlayer it should handle there the ConditionalBlocker.

If this change is done, it should be applied to Lurking Eel as well, which also has the same issue.

2024-10-14 13:56 UTC, DanieloV commented on game/cards/promo/demon_command.go
> +		}
Same as for AmnisHolyElemental

2024-10-16 12:49 UTC, jyotiskaghosh commented on game/cards/promo/angel_command.go
> +		}
This is a bit tricky. Conditional Blockers are still considered blockers, i.e., are effected by cards like Critical Blade. We'd need to refactor a lot to make it work as expected.

2024-11-06 00:53 UTC, merged