Dm-08 Implement dragon evolution. Add Bajula and Abzo Dolba.
sindreslungaard/duel-masters pull request #307
Opened 2024-12-06 18:53 UTC by jyotiskaghosh

dependent on #305

2025-02-16 17:24 UTC, sindreslungaard commented
Could you rebase this PR (and others where relevant) with the master branch seeing that there have been changes made to the branch this PR was branched off of that no longer should be included here. Stacking PR's like this also makes it much harder to review quickly as Github's "Files changed" feature does not work properly with it

2025-02-20 09:04 UTC, jyotiskaghosh commented
This depends on the Jagalzor PR #314. It will be easier to merge this after resolving that.

2025-02-27 19:26 UTC, DragosIonita23 commented on game/cards/dm08/armored_dragon.go
> +	c.Use(fx.Creature, fx.DragonEvolution, fx.Triplebreaker, fx.WheneverThisAttacks(fx.ManaBurnX(2)))
WheneverThisAttacks -> When(AttackConfirmed, ...)

2025-02-28 09:05 UTC, DragosIonita23 commented on game/cards/dm08/armored_dragon.go
> +	c.Use(fx.Creature, fx.DragonEvolution, fx.Triplebreaker, fx.WheneverThisAttacks(fx.ManaBurnX(2)))
I agree with Sindre on his comment regarding the stacking of PR's @jyotiskaghosh, I think it's better to jush have a single PR and push changes into it if you want to add / modify things, even after you created the PR

2025-03-01 11:52 UTC, jyotiskaghosh commented on game/cards/dm08/armored_dragon.go
> +	c.Use(fx.Creature, fx.DragonEvolution, fx.Triplebreaker, fx.WheneverThisAttacks(fx.ManaBurnX(2)))
Used to do that, but it was recommended and also said in the contributing guide to send in small batches. But yeah, stacking is also messy, from now on I'll create branches from a base branch.

2025-04-11 08:32 UTC, DragosIonita23 commented on game/fx/mana_burn.go
> +			fmt.Sprintf("Select upto %d card(s) from your opponent's mana zone that will be sent to their graveyard", x),
"up to"

2025-04-11 08:34 UTC, DragosIonita23 commented on game/fx/quality_of_life.go
> +		if creature, ok := card.Player.GetCard(event.Source, match.BATTLEZONE); ok == nil {
creature, error := card.Player.GetCard(....); error == nil {

2025-04-11 08:36 UTC, DragosIonita23 commented on game/fx/return_to.go
> +			fmt.Sprintf("%s: You may return %d creature(s) from your graveyard to your hand", card.Name, x),
"You **MAY** return X creatures from your grave ..." implies the Select action is cancellable, which here it is **NOT**.

Is this the case or it's a typo in the text?

2025-04-11 08:37 UTC, DragosIonita23 requested changes
small comments

2025-04-19 15:05 UTC, merged